CREATE TABLE `message_queue` (
`id` bigint(20) NOT NULL auto_increment,
`cbr_id` varchar(255) NOT NULL,
`source` varchar(255) NOT NULL,
`source_id` varchar(255) NOT NULL,
`source_attributes` longtext default NULL,
`batch` boolean default false,
`batch_index` int default 0,
`payload` longtext NOT NULL,
`cbr_recevied_time` varchar (255) NOT NULL,
`cbr_delivered_time` varchar (255) default NULL,
`sender` varchar (255) default NULL,
`recipient` varchar (255) default NULL,
`errorCode` varchar (255) default NULL,
`errorMessage` varchar (255) default NULL,
`attempts` int  default 0,
`status` varchar (255) default 'queued',
`created_at` varchar (255) default NULL,
`updated_at` varchar (255) default NULL,
 PRIMARY KEY (`id`))