---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      fabric8.io/git-commit: "2a48b9edba2c527d479a5551c67e065794ebbb5e"
      fabric8.io/iconUrl: "img/icons/camel.svg"
      fabric8.io/git-branch: "ProjectStructure"
    labels:
      expose: "true"
      provider: "fabric8"
      project: "sdp-cbr-core"
      version: "1.0.0-SNAPSHOT"
      group: "gov.cdc.sdp"
    name: "sdp-cbr-core"
  spec:
    ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "sdp-cbr-core"
      provider: "fabric8"
      group: "gov.cdc.sdp"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/git-commit: "2a48b9edba2c527d479a5551c67e065794ebbb5e"
      fabric8.io/iconUrl: "img/icons/camel.svg"
      fabric8.io/git-branch: "ProjectStructure"
      fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=sdp-cbr-core&var-version=1.0.0-SNAPSHOT"
    labels:
      provider: "fabric8"
      project: "sdp-cbr-core"
      version: "1.0.0-SNAPSHOT"
      group: "gov.cdc.sdp"
    name: "sdp-cbr-core"
  spec:
    replicas: 1
    selector:
      project: "sdp-cbr-core"
      provider: "fabric8"
      group: "gov.cdc.sdp"
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "2a48b9edba2c527d479a5551c67e065794ebbb5e"
          fabric8.io/iconUrl: "img/icons/camel.svg"
          fabric8.io/git-branch: "ProjectStructure"
          fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=sdp-cbr-core&var-version=1.0.0-SNAPSHOT"
        labels:
          provider: "fabric8"
          project: "sdp-cbr-core"
          version: "1.0.0-SNAPSHOT"
          group: "gov.cdc.sdp"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "sdp/sdp-cbr-core:snapshot-171031-142926-0046"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 180
          name: "spring-boot"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          - containerPort: 9779
            name: "prometheus"
            protocol: "TCP"
          - containerPort: 8778
            name: "jolokia"
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
            requests:
              cpu: "0.2"
          securityContext:
            privileged: false
    triggers:
    - type: "ConfigChange"
