apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: null
  name: sdpcbr-limits
spec:
  limits:
  - max:
      cpu: 750m
      memory: 3Gi
    min:
      cpu: 10m
      memory: 5Mi
    type: Pod
  - default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 750m
      memory: 3Gi
    maxLimitRequestRatio:
      cpu: "10"
    min:
      cpu: 10m
      memory: 5Mi
    type: Container
  - max:
      storage: 1Gi
    type: openshift.io/Image
  - max:
      openshift.io/images: "20"
    type: openshift.io/ImageStream
